version: "3"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password"
      - "RUBYLIB=./lib"
    command: |
      bash -c "grpc_tools_ruby_protoc -I ../protobuf --ruby_out=./lib --grpc_out=./lib ../protobuf/router.proto && \
      echo generate grpc_ruby_protoc  && \
      bundle exec ruby ./app/server/server.rb"
    volumes:
      - ./backend:/myapp
      - bundle:/usr/local/bundle
      - ./protobuf:/protobuf
    depends_on:
      - db
  db:
    image: postgres:10.1
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"

volumes:
  bundle:
